#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width         2
bspc config focused_border_color "#c77dff"
bspc config normal_border_color  "#240046"

sxhkd &
nitrogen --restore &
dunst &
~/.config/polybar/launch.sh &
sleep 3
picom &
